[{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1"},{"ContainerToolsException.Message":"無法判斷 Docker 目前設定為執行 Windows 或 Linux 容器。請確認 Docker 安裝在本機上且正在執行。若 Docker 已在執行，請嘗試將其重新啟動。","ContainerToolsException.ErrorCode":"CTC1004","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C busybox nslookup google.com' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C busybox nslookup google.com' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C ping nslookup google.com' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C ping nslookup google.com' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C ping google.com' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C ping google.com' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C ping google.com' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C ping google.com' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Docker command failed with exit code -2147450735.\r\nThe command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 2147516561","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"-2147450735","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 2147516561"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\nThe command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"The command 'cmd /S /C dotnet restore \"./graph.csproj\"' returned a non-zero code: 1"},{"ContainerToolsException.Message":"Visual Studio 容器工具需要 Docker 正在執行。","ContainerToolsException.ErrorCode":"CTC1003","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\npull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\npull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\npull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\npull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\npull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\npull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\npull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"},{"ContainerToolsException.Message":"Docker command failed with exit code 1.\r\npull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}]