[{"ContainerToolsException.Message":"Visual Studio 容器工具需要 Docker 正在執行。","ContainerToolsException.ErrorCode":"CTC1003","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"未啟用磁碟區共用。請在 Docker Desktop 的 [設定] 畫面上按一下 [共用磁碟機]，然後選取包含您專案檔的磁碟機。","ContainerToolsException.ErrorCode":"CTC1001","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"Docker command failed with exit code 125.\r\ndocker: Error response from daemon: Drive has not been shared.\r\nSee 'docker run --help'.","ContainerToolsException.ErrorCode":"CTC1015","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<RunContainerAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"run","ContainerToolsException.CommandLine.ExitCode":"125","ContainerToolsException.CommandLine.ErrorOutput":"docker: Error response from daemon: Drive has not been shared.\r\nSee 'docker run --help'."},{"ContainerToolsException.Message":"Docker command failed with exit code 125.\r\ndocker: Error response from daemon: Drive has not been shared.\r\nSee 'docker run --help'.","ContainerToolsException.ErrorCode":"CTC1015","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<RunContainerAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"run","ContainerToolsException.CommandLine.ExitCode":"125","ContainerToolsException.CommandLine.ErrorOutput":"docker: Error response from daemon: Drive has not been shared.\r\nSee 'docker run --help'."},{"ContainerToolsException.Message":"Docker Desktop 未如預期般運作。請嘗試重新啟動 Docker。","ContainerToolsException.ErrorCode":"CTC1006","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"Docker command failed with exit code 125.\r\ndocker: Error response from daemon: Drive has not been shared.\r\nSee 'docker run --help'.","ContainerToolsException.ErrorCode":"CTC1015","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<RunContainerAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"run","ContainerToolsException.CommandLine.ExitCode":"125","ContainerToolsException.CommandLine.ErrorOutput":"docker: Error response from daemon: Drive has not been shared.\r\nSee 'docker run --help'."},{"ContainerToolsException.Message":"Visual Studio 容器工具需要 Docker 正在執行。","ContainerToolsException.ErrorCode":"CTC1003","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"Docker Desktop 未如預期般運作。請嘗試重新啟動 Docker。","ContainerToolsException.ErrorCode":"CTC1006","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"未啟用磁碟區共用。請在 Docker Desktop 的 [設定] 畫面上按一下 [共用磁碟機]，然後選取包含您專案檔的磁碟機。","ContainerToolsException.ErrorCode":"CTC1001","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"Docker command failed with exit code 125.\r\ndocker: Error response from daemon: Drive has not been shared.\r\nSee 'docker run --help'.","ContainerToolsException.ErrorCode":"CTC1015","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<RunContainerAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"run","ContainerToolsException.CommandLine.ExitCode":"125","ContainerToolsException.CommandLine.ErrorOutput":"docker: Error response from daemon: Drive has not been shared.\r\nSee 'docker run --help'."},{"ContainerToolsException.Message":"因為下列連接埠已在使用中，所以無法啟動 Docker 容器: 25844, 44393","ContainerToolsException.ErrorCode":"CTC1011","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"launchSettings.json","ContainerToolsException.FaultingUserFile.LineStart":"26","ContainerToolsException.FaultingUserFile.ColumnStart":"16","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 125.\r\ndocker: Error response from daemon: driver failed programming external connectivity on endpoint wizardly_mendeleev (f6a891d604f0ed4187d931cc6e2edb82f59e1c0d9b7bac78e787f5876e6702da): Error starting userland proxy: listen tcp 0.0.0.0:44393: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<RunContainerAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n錯誤碼: CTC1015\r\n嚴重性: Error\r\n命令列: docker run -dt -v \"C:\\Users\\rex\\vsdbg\\vs2017u5:/remote_debugger:rw\" -v \"C:\\Users\\rex\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets:ro\" -v \"C:\\Users\\rex\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https:ro\" -e \"ASPNETCORE_ENVIRONMENT=Development\" -p 25844:80 -p 44393:443 --entrypoint tail graph -f /dev/null \r\n命令結束代碼: 125\r\n命令輸出: 8b7ae29f5926a3b8896b9c208bffc203c35f1cd73ae71280c106e8c3a5924224\r\n命令錯誤: docker: Error response from daemon: driver failed programming external connectivity on endpoint wizardly_mendeleev (f6a891d604f0ed4187d931cc6e2edb82f59e1c0d9b7bac78e787f5876e6702da): Error starting userland proxy: listen tcp 0.0.0.0:44393: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n"},{"ContainerToolsException.Message":"Visual Studio 容器工具需要 Docker 正在執行。","ContainerToolsException.ErrorCode":"CTC1003","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"Docker Desktop 未如預期般運作。請嘗試重新啟動 Docker。","ContainerToolsException.ErrorCode":"CTC1006","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088"},{"ContainerToolsException.Message":"因為下列連接埠已在使用中，所以無法啟動 Docker 容器: 25844, 44393","ContainerToolsException.ErrorCode":"CTC1011","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"launchSettings.json","ContainerToolsException.FaultingUserFile.LineStart":"26","ContainerToolsException.FaultingUserFile.ColumnStart":"16","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 125.\r\ndocker: Error response from daemon: driver failed programming external connectivity on endpoint dazzling_jackson (b2779c2b6881261d3fea7415c5dc9d3fa89f0c45568e7402b1dffac301b71a9f): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500.\r\n   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<RunContainerAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n錯誤碼: CTC1015\r\n嚴重性: Error\r\n命令列: docker run -dt -v \"C:\\Users\\rex\\vsdbg\\vs2017u5:/remote_debugger:rw\" -v \"C:\\Users\\rex\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets:ro\" -v \"C:\\Users\\rex\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https:ro\" -e \"ASPNETCORE_ENVIRONMENT=Development\" -p 25844:80 -p 44393:443 --entrypoint tail graph -f /dev/null \r\n命令結束代碼: 125\r\n命令輸出: b9f4704b118ceb9f8baeca8b6354a2bad41c2c6e88dfbc9308b4566ce3c4b069\r\n命令錯誤: docker: Error response from daemon: driver failed programming external connectivity on endpoint dazzling_jackson (b2779c2b6881261d3fea7415c5dc9d3fa89f0c45568e7402b1dffac301b71a9f): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500.\r\n"},{"ContainerToolsException.Message":"因為下列連接埠已在使用中，所以無法啟動 Docker 容器: 25844, 44393","ContainerToolsException.ErrorCode":"CTC1011","ContainerToolsException.StackTrace":"   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__156.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"launchSettings.json","ContainerToolsException.FaultingUserFile.LineStart":"26","ContainerToolsException.FaultingUserFile.ColumnStart":"16","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 125.\r\ndocker: Error response from daemon: driver failed programming external connectivity on endpoint reverent_mendel (f35663dfb8b7fc75fead1568969a51bede36899c4d0d5895a863184620e5eb57): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500.\r\n   於 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<RunContainerAsync>d__5.MoveNext()\r\n--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   於 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RecreateContainerAsync>d__12.MoveNext()\r\n錯誤碼: CTC1015\r\n嚴重性: Error\r\n命令列: docker run -dt -v \"C:\\Users\\rex\\vsdbg\\vs2017u5:/remote_debugger:rw\" -v \"C:\\Users\\rex\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets:ro\" -v \"C:\\Users\\rex\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https:ro\" -e \"ASPNETCORE_ENVIRONMENT=Development\" -p 25844:80 -p 44393:443 --entrypoint tail graph -f /dev/null \r\n命令結束代碼: 125\r\n命令輸出: 0e19b93133fa9a2cf50dfed7ffc2e5c49f8f7d4ee14e3968d20eb388f6febb9c\r\n命令錯誤: docker: Error response from daemon: driver failed programming external connectivity on endpoint reverent_mendel (f35663dfb8b7fc75fead1568969a51bede36899c4d0d5895a863184620e5eb57): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500.\r\n"}]